FROM node:24-alpine AS build

WORKDIR /app

ARG REACT_APP_API_URL
ARG REACT_APP_NFSE_API_URL
ARG REACT_APP_NFSE_API_KEY
ARG REACT_APP_NFSE_CODIGO_SERVICO

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_NFSE_API_URL=$REACT_APP_NFSE_API_URL
ENV REACT_APP_NFSE_API_KEY=$REACT_APP_NFSE_API_KEY
ENV REACT_APP_NFSE_CODIGO_SERVICO=$REACT_APP_NFSE_CODIGO_SERVICO

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
